---
output:
  pdf_document: default
always_allow_html: true
params:
  mon_ope: "88610"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```




```{r}
# devtools::install_github("pascalirz/aspe")
# devtools::install_github("pascalirz/ggplotExtra")
library(aspe)
library(ggplotExtra)
library(tidyverse)

load(file = "../processed_data/reg_data.RData")
```

```{r}
mon_libelle <- reg_ope %>% 
  filter(ope_id == params$mon_ope) %>% 
  pull(pop_libelle)

mon_pop <- reg_ope %>% 
  filter(ope_id == params$mon_ope) %>% 
  pull(pop_id)
```

>`r mon_libelle`


# Conditions de pêche lors des opérations

## Caractéristiques environnementales

```{r, fig.width = 9, dpi = 300}
reg_ope_env %>% 
  filter(pop_id == mon_pop,
         !(variable %in% c("Conductivité", "Intensité", "Tension", "Puissance"))
         ) %>% 
  ggplotExtra::gg_lattice_line(
  var_x = annee,
  var_y = valeur,
  var_lattice = variable,
  threshold_x = 2007,
  lab_y = "",
  free_y = TRUE
)
```

## Paramètres électriques


```{r, fig.width = 9, dpi = 300}
# reg_ope_env <- reg_donnees_env %>% 
#   filter(dept == params$mon_dept) 

reg_ope_env %>% 
  filter(
    pop_id == mon_pop,
    (variable %in% c("Conductivité", "Intensité", "Tension", "Puissance"))) %>% 
  ggplotExtra::gg_lattice_line(
  var_x = annee,
  var_y = valeur,
  var_lattice = variable,
  threshold_x = 2007,
  lab_y = "",
  free_y = TRUE
)
```

# IPR

```{r, fig.height = 4}
classe_ipr <- classe_ipr %>%
  aspe::ip_completer_classes_couleur()


pop_ipr <- reg_ope_ipr %>%
  filter(pop_id == mon_pop)

aspe::gg_temp_ipr(df_ipr = pop_ipr,
                  var_id_sta = pop_libelle,
                  var_ipr = ipr,
                  df_classes = classe_ipr) +
  labs(title = "") +
    theme(
    panel.grid.major.x = element_line(size = .2,
                                      color = "grey80"),
    panel.grid.major.y = element_blank(),
    legend.position = "right"
  ) +
  guides(fill = guide_legend(title = "Classe de qualité",
                             nrow = 5,
                             byrow = TRUE))
```

```{r, fig.width = 8, fig.height = 5.5}
reg_ope_metrique %>%
  filter(pop_id == mon_pop) %>%
  mutate(
    metrique = str_replace(
      string = metrique,
      pattern = "opi_",
      replacement = ""
    ),
    metrique = str_to_upper(metrique)
  ) %>%
  ggplotExtra::gg_lattice_ipr(
    var_y = valeur,
    var_lattice = metrique,
    metriques = TRUE,
    interactif = FALSE,
    df_classes = classe_ipr
  ) +
  theme(
    legend.position = "none",
    panel.grid.major.x = element_line(size = .2, color = "grey80"),
    panel.grid.major.y = element_blank()
  ) +
  ggtitle("Métriques constitutives de l'IPR")
```

# Les espèces

## Abondance numérique

```{r}
data <- reg_ope_capt %>%
  filter(ope_id == params$mon_ope,
         effectif > 0)

richesse <- n_distinct(data$esp_code_alternatif)
```


```{r, fig.height = richesse / 4}
data %>% 
  ggplot(aes(x = fct_reorder(esp_nom_commun, effectif),
             y = effectif)) +
  geom_bar(stat = "identity",
           fill = "darkgreen") +
  coord_flip() +
  labs(x = "",
       y = "Effectif capturé") +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())
```



## Probabilité de présence


```{r}
mon_point <- reg_ope_pp %>%
  filter(ope_id == params$mon_ope) %>%
  pull(pop_id) %>%
  unique()
   

test <- reg_ope_pp %>%
  filter(ope_id == params$mon_ope) %>%
  mutate(esp_nom_commun = fct_reorder(esp_nom_commun, ppi_valeur_probabilite),
         couleur = ifelse(presence == "Présence",
                          "#1B9E77",
                          "#D95F02")) %>%
  arrange(esp_nom_commun)

ma_station <- test %>%
  pull(pop_libelle) %>%
  unique()
```

```{r, fig.height = 4.5, dpi = 300}
ggplot(data = test,
       aes(x = esp_nom_commun,
           y = ppi_valeur_probabilite,
           fill = presence)) +
  geom_bar(stat = "identity",
           col = "white") +
  coord_flip() +
  labs(x = "",
       y = "Probabilité de présence",
       title = ma_station,
       fill = "") +
  scale_y_continuous(labels = scales::percent) +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.text = element_text(size = 8),
        axis.text.y = element_text(colour = test$couleur),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 9)) +
  scale_fill_brewer(palette = "Dark2", direction = -1)
```